#!/usr/bin/env bash
# Displays informtation about subdomains.


subdomains=( "www" "lb-01" "web-01" "web-02" )
domain=$1
sub=$2

get_dns_info() {
    local sub="$1"
    local domain="$2"
    INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
	IP=$(echo "$INFO" | awk '{print $5}')
	RECORD=$(echo "$INFO" | awk '{print $4}')

    echo -e "The subdomain $sub is a $RECORD record and points to $IP"
}

if [ "$#" -eq 1 ]; then
    for item in ${subdomains[@]}; do
        get_dns_info "$item" "$domain"
    done
elif [ "$#" -eq 2 ]; then
    get_dns_info "$sub" "$domain"
fi
    