#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i '/listen \[::\]:80 default_server;/a\\tlisten 80;' /etc/nginx/sites-available/default
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx restart
