#!/usr/bin/env bash
# Installs nginx and configures it on a remote server

echo -e "Updating and Installing nginx. \n"
sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y

echo  -e "Setting Up some stuffs\n"

# Starting nginx services
sudo service nginx start

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R 775 /var/www

# Backup dafault index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted. \n"
