#!/usr/bin/env bash 
# Manage my process

if [ $# -ne 1 ]; then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
else
	if [ "$1" = "start" ]; then
		bash ./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process started"
	elif [ "$1" = "stop" ]; then
		[ -e "/var/run/my_process.pid" ] && pkill -f './manage_my_process' && rm /var/run/my_process.pid
		echo "manage_my_process stopped"
	elif [ "$1" = "restart" ]; then
		"$0" stop >& /dev/null
		"$0" start >& /dev/null
		echo "manage_my_process restarted"
	else
		echo "Usage: manage_my_process {start|stop|restart}"
	fi
fi
